//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "asignaciones", uniqueConstraints = @UniqueConstraint(columnNames = {"idDependencia", "fechaDesde"}))

public class Asignaciones implements Serializable {

    @Column(name = "fechaHasta", table = "asignaciones")
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fechaHasta;

    @Column(name = "fechaDesde", table = "asignaciones", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fechaDesde;

    @ManyToOne(targetEntity = Notas.class)
    @JoinColumn(name = "idNota")
    private Notas idNota;

    @OneToMany(targetEntity = PatrimoniosXAsignaciones.class, mappedBy = "idAsignacion")
    private List<PatrimoniosXAsignaciones> patrimoniosXAsignacionesCollection;

    @ManyToOne(optional = false, targetEntity = Dependencias.class)
    @JoinColumn(name = "idDependencia")
    private Dependencias idDependencia;

    @Column(name = "idAsignacion", table = "asignaciones", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idAsignacion;
    
    @Column(name = "prestamo", table = "asignaciones", nullable = false)
    @Basic
    private boolean prestamo;

    public Asignaciones() {

    }

    public Date getFechaHasta() {
        return this.fechaHasta;
    }

    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }

    public Date getFechaDesde() {
        return this.fechaDesde;
    }

    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }

    public Notas getIdNota() {
        return this.idNota;
    }

    public void setIdNota(Notas idNota) {
        this.idNota = idNota;
    }

    public List<PatrimoniosXAsignaciones> getPatrimoniosXAsignacionesCollection() {
        return this.patrimoniosXAsignacionesCollection;
    }

    public void setPatrimoniosXAsignacionesCollection(List<PatrimoniosXAsignaciones> patrimoniosXAsignacionesCollection) {
        this.patrimoniosXAsignacionesCollection = patrimoniosXAsignacionesCollection;
    }

    public Dependencias getIdDependencia() {
        return this.idDependencia;
    }

    public void setIdDependencia(Dependencias idDependencia) {
        this.idDependencia = idDependencia;
    }

    public Integer getIdAsignacion() {
        return this.idAsignacion;
    }

    public void setIdAsignacion(Integer idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

    public boolean isPrestamo() {
        return prestamo;
    }

    public void setPrestamo(boolean prestamo) {
        this.prestamo = prestamo;
    }

    @Override
    public String toString() {
        return "Asignaciones{" + "fechaHasta=" + fechaHasta + ", idNota=" + idNota + ", idDependencia=" + idDependencia + ", idAsignacion=" + idAsignacion + ", resuelta=" + prestamo + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.idAsignacion);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Asignaciones other = (Asignaciones) obj;
        if (!Objects.equals(this.idAsignacion, other.idAsignacion)) {
            return false;
        }
        return true;
    }
    
}
