//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "caracteristicas")

public class Caracteristicas implements Serializable {

    @Column(name = "descripcion", table = "caracteristicas", length = 200)
    @Basic
    private String descripcion;

    @OneToMany(targetEntity = CaracteristicasXInsumo.class, mappedBy = "idCaracteristica")
    private List<CaracteristicasXInsumo> caracteristicasXInsumoCollection;

    @Column(name = "idCaracteristica", table = "caracteristicas", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idCaracteristica;

    @OneToMany(targetEntity = CaracteristicasXPonderaciones.class, mappedBy = "idCaracteristica")
    private List<CaracteristicasXPonderaciones> caracteristicasXPonderacionesCollection;

    @Column(name = "nombre", table = "caracteristicas", nullable = false, length = 100)
    @Basic
    private String nombre;

    public Caracteristicas() {

    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public List<CaracteristicasXInsumo> getCaracteristicasXInsumoCollection() {
        return this.caracteristicasXInsumoCollection;
    }

    public void setCaracteristicasXInsumoCollection(List<CaracteristicasXInsumo> caracteristicasXInsumoCollection) {
        this.caracteristicasXInsumoCollection = caracteristicasXInsumoCollection;
    }

    public Integer getIdCaracteristica() {
        return this.idCaracteristica;
    }

    public void setIdCaracteristica(Integer idCaracteristica) {
        this.idCaracteristica = idCaracteristica;
    }

    public List<CaracteristicasXPonderaciones> getCaracteristicasXPonderacionesCollection() {
        return this.caracteristicasXPonderacionesCollection;
    }

    public void setCaracteristicasXPonderacionesCollection(List<CaracteristicasXPonderaciones> caracteristicasXPonderacionesCollection) {
        this.caracteristicasXPonderacionesCollection = caracteristicasXPonderacionesCollection;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 17 * hash + Objects.hashCode(this.idCaracteristica);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Caracteristicas other = (Caracteristicas) obj;
        if (!Objects.equals(this.idCaracteristica, other.idCaracteristica)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombre;
    }
    
}
