//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "caracteristicasXInsumo", uniqueConstraints = @UniqueConstraint(columnNames = {"idCaracteristica", "idModelo"}))

public class CaracteristicasXInsumo implements Serializable {

    @Column(name = "idCarXIns", table = "caracteristicasXInsumo", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idCarXIns;

    @Column(name = "valor", table = "caracteristicasXInsumo", nullable = false)
    @Basic
    private double valor;

    @ManyToOne(optional = false, targetEntity = Caracteristicas.class)
    @JoinColumn(name = "idCaracteristica")
    private Caracteristicas idCaracteristica;

    @ManyToOne(optional = false, targetEntity = ModelosInsumo.class)
    @JoinColumn(name = "idModelo")
    private ModelosInsumo idModelo;

    public CaracteristicasXInsumo() {

    }

    public Integer getIdCarXIns() {
        return this.idCarXIns;
    }

    public void setIdCarXIns(Integer idCarXIns) {
        this.idCarXIns = idCarXIns;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public Caracteristicas getIdCaracteristica() {
        return this.idCaracteristica;
    }

    public void setIdCaracteristica(Caracteristicas idCaracteristica) {
        this.idCaracteristica = idCaracteristica;
    }

    public ModelosInsumo getIdModelo() {
        return this.idModelo;
    }

    public void setIdModelo(ModelosInsumo idModelo) {
        this.idModelo = idModelo;
    }
}
