//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "caracteristicasXPonderaciones", uniqueConstraints = @UniqueConstraint(columnNames = {"idCaracteristica", "idPonderacion"}))

public class CaracteristicasXPonderaciones implements Serializable {

    @Column(name = "valor", table = "caracteristicasXPonderaciones", nullable = false)
    @Basic
    private double valor;

    @ManyToOne(optional = false, targetEntity = Caracteristicas.class)
    @JoinColumn(name = "idCaracteristica")
    private Caracteristicas idCaracteristica;

    @ManyToOne(optional = false, targetEntity = UnidadMedida.class)
    @JoinColumn(name = "idUnidadMedida")
    private UnidadMedida idUnidadMedida;

    @ManyToOne(optional = false, targetEntity = Ponderaciones.class)
    @JoinColumn(name = "idPonderacion")
    private Ponderaciones idPonderacion;

    @Column(name = "IdCarXPon", table = "caracteristicasXPonderaciones", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idCarXPon;

    public CaracteristicasXPonderaciones() {

    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public Caracteristicas getIdCaracteristica() {
        return this.idCaracteristica;
    }

    public void setIdCaracteristica(Caracteristicas idCaracteristica) {
        this.idCaracteristica = idCaracteristica;
    }

    public UnidadMedida getIdUnidadMedida() {
        return this.idUnidadMedida;
    }

    public void setIdUnidadMedida(UnidadMedida idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }

    public Ponderaciones getIdPonderacion() {
        return this.idPonderacion;
    }

    public void setIdPonderacion(Ponderaciones idPonderacion) {
        this.idPonderacion = idPonderacion;
    }

    public Integer getIdCarXPon() {
        return this.idCarXPon;
    }

    public void setIdCarXPon(Integer idCarXPon) {
        this.idCarXPon = idCarXPon;
    }
}
