//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "elementosUtilizados", uniqueConstraints = @UniqueConstraint(columnNames = {"idEstadoXTrabajo", "idInsumo"}))

public class ElementosUtilizados implements Serializable {

    @ManyToOne(optional = false, targetEntity = EstadosXTrabajo.class)
    @JoinColumn(name = "idEstadoXTrabajo")
    private EstadosXTrabajo idEstadoXTrabajo;

    @ManyToOne(optional = false, targetEntity = InsumosDisponibles.class)
    @JoinColumn(name = "idInsumo")
    private InsumosDisponibles idInsumo;

    @Column(name = "observaciones", table = "elementosUtilizados", length = 500)
    @Basic
    private String observaciones;

    @Column(name = "idElemento", table = "elementosUtilizados", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idElemento;

    @Column(name = "cantidad", table = "elementosUtilizados", nullable = false)
    @Basic
    private double cantidad;

    public ElementosUtilizados() {

    }

    public EstadosXTrabajo getIdEstadoXTrabajo() {
        return this.idEstadoXTrabajo;
    }

    public void setIdEstadoXTrabajo(EstadosXTrabajo idEstadoXTrabajo) {
        this.idEstadoXTrabajo = idEstadoXTrabajo;
    }

    public InsumosDisponibles getIdInsumo() {
        return this.idInsumo;
    }

    public void setIdInsumo(InsumosDisponibles idInsumo) {
        this.idInsumo = idInsumo;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public Integer getIdElemento() {
        return this.idElemento;
    }

    public void setIdElemento(Integer idElemento) {
        this.idElemento = idElemento;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + Objects.hashCode(this.idElemento);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ElementosUtilizados other = (ElementosUtilizados) obj;
        if (!Objects.equals(this.idElemento, other.idElemento)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ElementosUtilizados{" + "idEstadoXTrabajo=" + idEstadoXTrabajo + ", idInsumo=" + idInsumo + ", cantidad=" + cantidad + '}';
    }
    
}
