//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "encargados")

public class Encargados implements Serializable {

    @Column(name = "idEncargado", table = "encargados", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idEncargado;

    @Column(name = "apellido", table = "encargados", nullable = false, length = 45)
    @Basic
    private String apellido;

    @OneToMany(targetEntity = Dependencias.class, mappedBy = "idEncargado")
    private List<Dependencias> dependenciasCollection;

    @Column(name = "nombre", table = "encargados", nullable = false, length = 45)
    @Basic
    private String nombre;

    public Encargados() {

    }

    public Integer getIdEncargado() {
        return this.idEncargado;
    }

    public void setIdEncargado(Integer idEncargado) {
        this.idEncargado = idEncargado;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public List<Dependencias> getDependenciasCollection() {
        return this.dependenciasCollection;
    }

    public void setDependenciasCollection(List<Dependencias> dependenciasCollection) {
        this.dependenciasCollection = dependenciasCollection;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
