//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "entregaInsumos")

public class EntregaInsumos implements Serializable {

    @Column(name = "idEntregaInsumo", table = "entregaInsumos", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idEntregaInsumo;

    @Column(name = "fecha", table = "entregaInsumos", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fecha;

    @ManyToOne(optional = false, targetEntity = Usuarios.class)
    @JoinColumn(name = "usuarioIniciador")
    private Usuarios usuarioIniciador;

    @OneToMany(targetEntity = LineaEntrega.class, mappedBy = "idEntregaInsumo")
    private List<LineaEntrega> lineaEntregaCollection;

    @ManyToOne(targetEntity = Notas.class)
    @JoinColumn(name = "idNota")
    private Notas idNota;

    @ManyToOne(optional = false, targetEntity = Dependencias.class)
    @JoinColumn(name = "idDependencia")
    private Dependencias idDependencia;

    @ManyToOne(optional = false, targetEntity = Tecnicos.class)
    @JoinColumn(name = "idTecnico")
    private Tecnicos idTecnico;

    @Column(name = "observacion", table = "entregaInsumos", length = 100)
    @Basic
    private String observacion;

    public EntregaInsumos() {

    }

    public Integer getIdEntregaInsumo() {
        return this.idEntregaInsumo;
    }

    public void setIdEntregaInsumo(Integer idEntregaInsumo) {
        this.idEntregaInsumo = idEntregaInsumo;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Usuarios getUsuarioIniciador() {
        return this.usuarioIniciador;
    }

    public void setUsuarioIniciador(Usuarios usuarioIniciador) {
        this.usuarioIniciador = usuarioIniciador;
    }

    public List<LineaEntrega> getLineaEntregaCollection() {
        return this.lineaEntregaCollection;
    }

    public void setLineaEntregaCollection(List<LineaEntrega> lineaEntregaCollection) {
        this.lineaEntregaCollection = lineaEntregaCollection;
    }

    public Notas getIdNota() {
        return this.idNota;
    }

    public void setIdNota(Notas idNota) {
        this.idNota = idNota;
    }

    public Dependencias getIdDependencia() {
        return this.idDependencia;
    }

    public void setIdDependencia(Dependencias idDependencia) {
        this.idDependencia = idDependencia;
    }

    public Tecnicos getIdTecnico() {
        return this.idTecnico;
    }

    public void setIdTecnico(Tecnicos idTecnico) {
        this.idTecnico = idTecnico;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 73 * hash + Objects.hashCode(this.idEntregaInsumo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EntregaInsumos other = (EntregaInsumos) obj;
        if (!Objects.equals(this.idEntregaInsumo, other.idEntregaInsumo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "EntregaInsumos{" + "fecha=" + fecha + ", usuarioIniciador=" + usuarioIniciador + ", idDependencia=" + idDependencia + '}';
    }
    
}
