//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "estadosTrabajo")

public class EstadosTrabajo implements Serializable {
    
    @Column(name = "descripcion", table = "estadosTrabajo", length = 100)
    @Basic
    private String descripcion;

    @Column(name = "estado", table = "estadosTrabajo", nullable = false, length = 45)
    @Id
    private String estado;

    @OneToMany(targetEntity = TransicionesEstado.class, mappedBy = "estadoSiguiente")
    private List<TransicionesEstado> transicionesEstadoCollection1;

    @OneToMany(targetEntity = EstadosXTrabajo.class, mappedBy = "estado")
    private List<EstadosXTrabajo> estadosXTrabajoCollection;

    @OneToMany(targetEntity = TransicionesEstado.class, mappedBy = "estado")
    private List<TransicionesEstado> transicionesEstadoCollection;

    public EstadosTrabajo() {

    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public List<TransicionesEstado> getTransicionesEstadoCollection1() {
        return this.transicionesEstadoCollection1;
    }

    public void setTransicionesEstadoCollection1(List<TransicionesEstado> transicionesEstadoCollection1) {
        this.transicionesEstadoCollection1 = transicionesEstadoCollection1;
    }

    public List<EstadosXTrabajo> getEstadosXTrabajoCollection() {
        return this.estadosXTrabajoCollection;
    }

    public void setEstadosXTrabajoCollection(List<EstadosXTrabajo> estadosXTrabajoCollection) {
        this.estadosXTrabajoCollection = estadosXTrabajoCollection;
    }

    public List<TransicionesEstado> getTransicionesEstadoCollection() {
        return this.transicionesEstadoCollection;
    }

    public void setTransicionesEstadoCollection(List<TransicionesEstado> transicionesEstadoCollection) {
        this.transicionesEstadoCollection = transicionesEstadoCollection;
    }

    @Override
    public String toString() {
        return "EstadosTrabajo{" + "estado=" + estado + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + Objects.hashCode(this.estado);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EstadosTrabajo other = (EstadosTrabajo) obj;
        if (!Objects.equals(this.estado, other.estado)) {
            return false;
        }
        return true;
    }
    
}
