//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "estadosXTrabajo", uniqueConstraints = @UniqueConstraint(columnNames = {"idTrabajo", "estado", "fechaDesde"}))

public class EstadosXTrabajo implements Serializable {

    @Column(name = "idEstadoXTrabajo", table = "estadosXTrabajo", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idEstadoXTrabajo;

    @Column(name = "trabajoRealizado", table = "estadosXTrabajo", nullable = false, length = 1000)
    @Basic
    private String trabajoRealizado;

    @ManyToOne(optional = false, targetEntity = EstadosTrabajo.class)
    @JoinColumn(name = "estado")
    private EstadosTrabajo estado;

    @Column(name = "fechaHasta", table = "estadosXTrabajo")
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fechaHasta;

    @Column(name = "nroFicha", table = "estadosXTrabajo", nullable = false)
    @Basic
    private int nroFicha;

    @ManyToOne(optional = false, targetEntity = Trabajos.class)
    @JoinColumn(name = "idTrabajo")
    private Trabajos idTrabajo;

    @Column(name = "fechaDesde", table = "estadosXTrabajo", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fechaDesde;

    @Column(name = "observaciones", table = "estadosXTrabajo", length = 1000)
    @Basic
    private String observaciones;

    @Column(name = "trabajoFirmado", table = "estadosXTrabajo", nullable = false)
    @Basic
    private boolean trabajoFirmado;

    @OneToMany(targetEntity = TecnicosXTrabajos.class, mappedBy = "idEstadoXTrabajo")
    private List<TecnicosXTrabajos> tecnicosXTrabajosCollection;

    @OneToMany(targetEntity = ElementosUtilizados.class, mappedBy = "idEstadoXTrabajo")
    private List<ElementosUtilizados> elementosUtilizadosCollection;

    @OneToMany(targetEntity = TareasRealizadas.class, mappedBy = "idEstadoXTrabajo")
    private List<TareasRealizadas> tareasRealizadasCollection;

    public EstadosXTrabajo() {

    }

    public Integer getIdEstadoXTrabajo() {
        return this.idEstadoXTrabajo;
    }

    public void setIdEstadoXTrabajo(Integer idEstadoXTrabajo) {
        this.idEstadoXTrabajo = idEstadoXTrabajo;
    }

    public String getTrabajoRealizado() {
        return this.trabajoRealizado;
    }

    public void setTrabajoRealizado(String trabajoRealizado) {
        this.trabajoRealizado = trabajoRealizado;
    }

    public EstadosTrabajo getEstado() {
        return this.estado;
    }

    public void setEstado(EstadosTrabajo estado) {
        this.estado = estado;
    }

    public Date getFechaHasta() {
        return this.fechaHasta;
    }

    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }

    public int getNroFicha() {
        return this.nroFicha;
    }

    public void setNroFicha(int nroFicha) {
        this.nroFicha = nroFicha;
    }

    public Trabajos getIdTrabajo() {
        return this.idTrabajo;
    }

    public void setIdTrabajo(Trabajos idTrabajo) {
        this.idTrabajo = idTrabajo;
    }

    public Date getFechaDesde() {
        return this.fechaDesde;
    }

    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public boolean isTrabajoFirmado() {
        return this.trabajoFirmado;
    }

    public void setTrabajoFirmado(boolean trabajoFirmado) {
        this.trabajoFirmado = trabajoFirmado;
    }

    public List<TecnicosXTrabajos> getTecnicosXTrabajosCollection() {
        return this.tecnicosXTrabajosCollection;
    }

    public void setTecnicosXTrabajosCollection(List<TecnicosXTrabajos> tecnicosXTrabajosCollection) {
        this.tecnicosXTrabajosCollection = tecnicosXTrabajosCollection;
    }

    public List<ElementosUtilizados> getElementosUtilizadosCollection() {
        return this.elementosUtilizadosCollection;
    }

    public void setElementosUtilizadosCollection(List<ElementosUtilizados> elementosUtilizadosCollection) {
        this.elementosUtilizadosCollection = elementosUtilizadosCollection;
    }

    public List<TareasRealizadas> getTareasRealizadasCollection() {
        return this.tareasRealizadasCollection;
    }

    public void setTareasRealizadasCollection(List<TareasRealizadas> tareasRealizadasCollection) {
        this.tareasRealizadasCollection = tareasRealizadasCollection;
    }
}
