//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "insumosDisponibles")

public class InsumosDisponibles implements Serializable {

    @Column(name = "idInsumo", table = "insumosDisponibles", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idInsumo;

    @OneToMany(targetEntity = LineaEntrega.class, mappedBy = "idInsumo")
    private List<LineaEntrega> lineaEntregaCollection;

    @OneToMany(targetEntity = InsumosXPatrimonio.class, mappedBy = "idInsumo")
    private List<InsumosXPatrimonio> insumosXPatrimonioCollection;

    @ManyToOne(optional = false, targetEntity = ModelosInsumo.class)
    @JoinColumn(name = "idModelo")
    private ModelosInsumo idModelo;

    @OneToMany(targetEntity = ElementosUtilizados.class, mappedBy = "idInsumo")
    private List<ElementosUtilizados> elementosUtilizadosCollection;

    @Column(name = "cantidadDisponible", table = "insumosDisponibles", nullable = false)
    @Basic
    private double cantidadDisponible;

    public InsumosDisponibles() {

    }

    public Integer getIdInsumo() {
        return this.idInsumo;
    }

    public void setIdInsumo(Integer idInsumo) {
        this.idInsumo = idInsumo;
    }

    public List<LineaEntrega> getLineaEntregaCollection() {
        return this.lineaEntregaCollection;
    }

    public void setLineaEntregaCollection(List<LineaEntrega> lineaEntregaCollection) {
        this.lineaEntregaCollection = lineaEntregaCollection;
    }

    public List<InsumosXPatrimonio> getInsumosXPatrimonioCollection() {
        return this.insumosXPatrimonioCollection;
    }

    public void setInsumosXPatrimonioCollection(List<InsumosXPatrimonio> insumosXPatrimonioCollection) {
        this.insumosXPatrimonioCollection = insumosXPatrimonioCollection;
    }

    public ModelosInsumo getIdModelo() {
        return this.idModelo;
    }

    public void setIdModelo(ModelosInsumo idModelo) {
        this.idModelo = idModelo;
    }

    public List<ElementosUtilizados> getElementosUtilizadosCollection() {
        return this.elementosUtilizadosCollection;
    }

    public void setElementosUtilizadosCollection(List<ElementosUtilizados> elementosUtilizadosCollection) {
        this.elementosUtilizadosCollection = elementosUtilizadosCollection;
    }

    public double getCantidadDisponible() {
        return this.cantidadDisponible;
    }

    public void setCantidadDisponible(double cantidadDisponible) {
        this.cantidadDisponible = cantidadDisponible;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.idInsumo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final InsumosDisponibles other = (InsumosDisponibles) obj;
        if (!Objects.equals(this.idInsumo, other.idInsumo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "InsumosDisponibles{" + "idModelo=" + idModelo + ", cantidadDisponible=" + cantidadDisponible + '}';
    }
    
}
