//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "marcas")

public class Marcas implements Serializable {

    @Column(name = "marca", table = "marcas", nullable = false, length = 100)
    @Basic
    private String marca;

    @Column(name = "paginaWeb", table = "marcas", length = 100)
    @Basic
    private String paginaWeb;

    @Column(name = "abreviatura", table = "marcas", length = 45)
    @Basic
    private String abreviatura;

    @OneToMany(targetEntity = ModelosInsumo.class, mappedBy = "idMarca")
    private List<ModelosInsumo> modelosInsumoCollection;

    @Column(name = "idMarca", table = "marcas", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idMarca;

    public Marcas() {

    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getPaginaWeb() {
        return this.paginaWeb;
    }

    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }

    public String getAbreviatura() {
        return this.abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public List<ModelosInsumo> getModelosInsumoCollection() {
        return this.modelosInsumoCollection;
    }

    public void setModelosInsumoCollection(List<ModelosInsumo> modelosInsumoCollection) {
        this.modelosInsumoCollection = modelosInsumoCollection;
    }

    public Integer getIdMarca() {
        return this.idMarca;
    }

    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 19 * hash + Objects.hashCode(this.idMarca);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Marcas other = (Marcas) obj;
        if (!Objects.equals(this.idMarca, other.idMarca)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return marca;
    }
    
}
