//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "medicionXTabla", uniqueConstraints = @UniqueConstraint(columnNames = {"idMedicion", "tabla"}))

public class MedicionXTabla implements Serializable {

    @Column(name = "valor", table = "medicionXTabla", nullable = false)
    @Basic
    private double valor;

    @ManyToOne(optional = false, targetEntity = MedicionTamanioTabla.class)
    @JoinColumn(name = "idMedicion")
    private MedicionTamanioTabla idMedicion;

    @ManyToOne(optional = false, targetEntity = Tablas.class)
    @JoinColumn(name = "tabla")
    private Tablas tabla;

    @Column(name = "idMedicionXTabla", table = "medicionXTabla", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idMedicionXTabla;

    public MedicionXTabla() {

    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public MedicionTamanioTabla getIdMedicion() {
        return this.idMedicion;
    }

    public void setIdMedicion(MedicionTamanioTabla idMedicion) {
        this.idMedicion = idMedicion;
    }

    public Tablas getTabla() {
        return this.tabla;
    }

    public void setTabla(Tablas tabla) {
        this.tabla = tabla;
    }

    public Integer getIdMedicionXTabla() {
        return this.idMedicionXTabla;
    }

    public void setIdMedicionXTabla(Integer idMedicionXTabla) {
        this.idMedicionXTabla = idMedicionXTabla;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.idMedicionXTabla);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MedicionXTabla other = (MedicionXTabla) obj;
        if (!Objects.equals(this.idMedicionXTabla, other.idMedicionXTabla)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "MedicionXTabla{" + "valor=" + valor + ", idMedicion=" + idMedicion + ", tabla=" + tabla + '}';
    }
    
}
