//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import java.util.logging.Logger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "modelosInsumo")

public class ModelosInsumo implements Serializable {

    @ManyToOne(optional = false, targetEntity = TipoInsumo.class)
    @JoinColumn(name = "idTipoInsumo")
    private TipoInsumo idTipoInsumo;

    @OneToMany(targetEntity = CaracteristicasXInsumo.class, mappedBy = "idModelo")
    private List<CaracteristicasXInsumo> caracteristicasXInsumoCollection;

    @OneToMany(targetEntity = InsumosDisponibles.class, mappedBy = "idModelo")
    private List<InsumosDisponibles> insumosDisponiblesCollection;

    @ManyToOne(optional = false, targetEntity = UnidadMedida.class)
    @JoinColumn(name = "idUnidadMedida")
    private UnidadMedida idUnidadMedida;

    @Column(name = "idModelo", table = "modelosInsumo", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idModelo;

    @ManyToOne(optional = false, targetEntity = Marcas.class)
    @JoinColumn(name = "idMarca")
    private Marcas idMarca;

    @Column(name = "modelo", table = "modelosInsumo", nullable = false, length = 100)
    @Basic
    private String modelo;

    public ModelosInsumo() {

    }

    public TipoInsumo getIdTipoInsumo() {
        return this.idTipoInsumo;
    }

    public void setIdTipoInsumo(TipoInsumo idTipoInsumo) {
        this.idTipoInsumo = idTipoInsumo;
    }

    public List<CaracteristicasXInsumo> getCaracteristicasXInsumoCollection() {
        return this.caracteristicasXInsumoCollection;
    }

    public void setCaracteristicasXInsumoCollection(List<CaracteristicasXInsumo> caracteristicasXInsumoCollection) {
        this.caracteristicasXInsumoCollection = caracteristicasXInsumoCollection;
    }

    public List<InsumosDisponibles> getInsumosDisponiblesCollection() {
        return this.insumosDisponiblesCollection;
    }

    public void setInsumosDisponiblesCollection(List<InsumosDisponibles> insumosDisponiblesCollection) {
        this.insumosDisponiblesCollection = insumosDisponiblesCollection;
    }

    public UnidadMedida getIdUnidadMedida() {
        return this.idUnidadMedida;
    }

    public void setIdUnidadMedida(UnidadMedida idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }

    public Integer getIdModelo() {
        return this.idModelo;
    }

    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }

    public Marcas getIdMarca() {
        return this.idMarca;
    }

    public void setIdMarca(Marcas idMarca) {
        this.idMarca = idMarca;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.idModelo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ModelosInsumo other = (ModelosInsumo) obj;
        if (!Objects.equals(this.idModelo, other.idModelo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ModelosInsumo{" + "idTipoInsumo=" + idTipoInsumo + ", idUnidadMedida=" + idUnidadMedida + ", idMarca=" + idMarca + ", modelo=" + modelo + '}';
    }
        
}
