//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "notas")

public class Notas implements Serializable {

    @OneToMany(targetEntity = EntregaInsumos.class, mappedBy = "idNota")
    private List<EntregaInsumos> entregaInsumosCollection;

    @Column(name = "fecha", table = "notas", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fecha;

    @OneToMany(targetEntity = Asignaciones.class, mappedBy = "idNota")
    private List<Asignaciones> asignacionesCollection;

    @ManyToOne(optional = false, targetEntity = TipoNota.class)
    @JoinColumn(name = "idTipoNota")
    private TipoNota idTipoNota;

    @Column(name = "imagen", table = "notas")
    @Lob
    @Basic
    private byte[] imagen;

    @Column(name = "idNota", table = "notas", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idNota;

    @ManyToOne(optional = false, targetEntity = Dependencias.class)
    @JoinColumn(name = "idDependenciaOrigen")
    private Dependencias idDependenciaOrigen;

    @OneToMany(targetEntity = Trabajos.class, mappedBy = "idNota")
    private List<Trabajos> trabajosCollection;

    @Column(name = "nroNota", table = "notas", nullable = false, length = 45)
    @Basic
    private String nroNota;

    @Column(name = "observacion", table = "notas", length = 500)
    @Basic
    private String observacion;

    @ManyToOne(optional = false, targetEntity = Dependencias.class)
    @JoinColumn(name = "idDependenciaDestino")
    private Dependencias idDependenciaDestino;

    public Notas() {

    }

    public List<EntregaInsumos> getEntregaInsumosCollection() {
        return this.entregaInsumosCollection;
    }

    public void setEntregaInsumosCollection(List<EntregaInsumos> entregaInsumosCollection) {
        this.entregaInsumosCollection = entregaInsumosCollection;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public List<Asignaciones> getAsignacionesCollection() {
        return this.asignacionesCollection;
    }

    public void setAsignacionesCollection(List<Asignaciones> asignacionesCollection) {
        this.asignacionesCollection = asignacionesCollection;
    }

    public TipoNota getIdTipoNota() {
        return this.idTipoNota;
    }

    public void setIdTipoNota(TipoNota idTipoNota) {
        this.idTipoNota = idTipoNota;
    }

    public byte[] getImagen() {
        return this.imagen;
    }

    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }

    public Integer getIdNota() {
        return this.idNota;
    }

    public void setIdNota(Integer idNota) {
        this.idNota = idNota;
    }

    public Dependencias getIdDependenciaOrigen() {
        return this.idDependenciaOrigen;
    }

    public void setIdDependenciaOrigen(Dependencias idDependenciaOrigen) {
        this.idDependenciaOrigen = idDependenciaOrigen;
    }

    public List<Trabajos> getTrabajosCollection() {
        return this.trabajosCollection;
    }

    public void setTrabajosCollection(List<Trabajos> trabajosCollection) {
        this.trabajosCollection = trabajosCollection;
    }

    public String getNroNota() {
        return this.nroNota;
    }

    public void setNroNota(String nroNota) {
        this.nroNota = nroNota;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Dependencias getIdDependenciaDestino() {
        return this.idDependenciaDestino;
    }

    public void setIdDependenciaDestino(Dependencias idDependenciaDestino) {
        this.idDependenciaDestino = idDependenciaDestino;
    }
}
