//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "patrimoniosXAsignaciones", uniqueConstraints = @UniqueConstraint(columnNames = {"idAsignacion", "idPatrimonio"}))

public class PatrimoniosXAsignaciones implements Serializable {

    @ManyToOne(optional = false, targetEntity = Patrimonios.class)
    @JoinColumn(name = "idPatrimonio")
    private Patrimonios idPatrimonio;

    @ManyToOne(optional = false, targetEntity = Asignaciones.class)
    @JoinColumn(name = "idAsignacion")
    private Asignaciones idAsignacion;

    @Column(name = "idPatXAsig", table = "patrimoniosXAsignaciones", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idPatXAsig;

    public PatrimoniosXAsignaciones() {

    }

    public Patrimonios getIdPatrimonio() {
        return this.idPatrimonio;
    }

    public void setIdPatrimonio(Patrimonios idPatrimonio) {
        this.idPatrimonio = idPatrimonio;
    }

    public Asignaciones getIdAsignacion() {
        return this.idAsignacion;
    }

    public void setIdAsignacion(Asignaciones idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

    public Integer getIdPatXAsig() {
        return this.idPatXAsig;
    }

    public void setIdPatXAsig(Integer idPatXAsig) {
        this.idPatXAsig = idPatXAsig;
    }
}
