//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "patrimoniosXAsignaciones", uniqueConstraints = @UniqueConstraint(columnNames = {"idAsignacion", "idPatrimonio"}))

public class PatrimoniosXAsignaciones implements Serializable {

    @ManyToOne(optional = false, targetEntity = Patrimonios.class)
    @JoinColumn(name = "idPatrimonio")
    private Patrimonios idPatrimonio;

    @ManyToOne(optional = false, targetEntity = Asignaciones.class)
    @JoinColumn(name = "idAsignacion")
    private Asignaciones idAsignacion;

    @Column(name = "idPatXAsig", table = "patrimoniosXAsignaciones", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idPatXAsig;
    
    @Column(name = "fechaDesde", table = "patrimoniosXAsignaciones", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date fechaDesde;
    
    @Column(name = "prestado", table = "patrimoniosXAsignaciones", nullable = false)
    @Basic
    private boolean prestado;

    public PatrimoniosXAsignaciones() {

    }

    public Patrimonios getIdPatrimonio() {
        return this.idPatrimonio;
    }

    public void setIdPatrimonio(Patrimonios idPatrimonio) {
        this.idPatrimonio = idPatrimonio;
    }

    public Asignaciones getIdAsignacion() {
        return this.idAsignacion;
    }

    public void setIdAsignacion(Asignaciones idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

    public Integer getIdPatXAsig() {
        return this.idPatXAsig;
    }

    public void setIdPatXAsig(Integer idPatXAsig) {
        this.idPatXAsig = idPatXAsig;
    }

    public Date getFechaDesde() {
        return fechaDesde;
    }

    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }

    public boolean isPrestado() {
        return prestado;
    }

    public void setPrestado(boolean prestado) {
        this.prestado = prestado;
    }
    
    @Override
    public String toString() {
        return "PatrimoniosXAsignaciones{" + "idPatrimonio=" + idPatrimonio + ", idAsignacion=" + idAsignacion + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.idPatXAsig);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PatrimoniosXAsignaciones other = (PatrimoniosXAsignaciones) obj;
        if (!Objects.equals(this.idPatXAsig, other.idPatXAsig)) {
            return false;
        }
        return true;
    }
    
}
