//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "prioridades")

public class Prioridades implements Serializable {

    @Column(name = "idPrioridad", table = "prioridades", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idPrioridad;

    @OneToMany(targetEntity = Trabajos.class, mappedBy = "idPrioridad")
    private List<Trabajos> trabajosCollection;

    @Column(name = "prioridad", table = "prioridades", nullable = false, length = 50)
    @Basic
    private String prioridad;

    public Prioridades() {

    }

    public Integer getIdPrioridad() {
        return this.idPrioridad;
    }

    public void setIdPrioridad(Integer idPrioridad) {
        this.idPrioridad = idPrioridad;
    }

    public List<Trabajos> getTrabajosCollection() {
        return this.trabajosCollection;
    }

    public void setTrabajosCollection(List<Trabajos> trabajosCollection) {
        this.trabajosCollection = trabajosCollection;
    }

    public String getPrioridad() {
        return this.prioridad;
    }

    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }
}
