//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "problemasN1")

public class ProblemasN1 implements Serializable {
    
    public static final int LONG_MAX_PROBLEMA= 45;

    @Column(name = "idProblemaN1", table = "problemasN1", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idProblemaN1;

    @OneToMany(targetEntity = ProblemasN2.class, mappedBy = "idProblemaN1")
    private List<ProblemasN2> problemasN2Collection;

    @Column(name = "problema", table = "problemasN1", nullable = false, length = 45)
    @Basic
    private String problema;

    public ProblemasN1() {

    }

    public Integer getIdProblemaN1() {
        return this.idProblemaN1;
    }

    public void setIdProblemaN1(Integer idProblemaN1) {
        this.idProblemaN1 = idProblemaN1;
    }

    public List<ProblemasN2> getProblemasN2Collection() {
        return this.problemasN2Collection;
    }

    public void setProblemasN2Collection(List<ProblemasN2> problemasN2Collection) {
        this.problemasN2Collection = problemasN2Collection;
    }

    public String getProblema() {
        return this.problema;
    }

    public void setProblema(String problema) {
        this.problema = problema;
    }

    @Override
    public String toString() {
        return problema;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + Objects.hashCode(this.idProblemaN1);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ProblemasN1 other = (ProblemasN1) obj;
        if (!Objects.equals(this.idProblemaN1, other.idProblemaN1)) {
            return false;
        }
        return true;
    }
       
    
}
