//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "tareasRealizadas", uniqueConstraints = @UniqueConstraint(columnNames = {"idTarea", "idEstadoXTrabajo"}))

public class TareasRealizadas implements Serializable {

    @ManyToOne(optional = false, targetEntity = EstadosXTrabajo.class)
    @JoinColumn(name = "idEstadoXTrabajo")
    private EstadosXTrabajo idEstadoXTrabajo;

    @ManyToOne(optional = false, targetEntity = Tareas.class)
    @JoinColumn(name = "idTarea")
    private Tareas idTarea;

    @Column(name = "idTareaXTrabajo", table = "tareasRealizadas", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTareaXTrabajo;

    public TareasRealizadas() {

    }

    public EstadosXTrabajo getIdEstadoXTrabajo() {
        return this.idEstadoXTrabajo;
    }

    public void setIdEstadoXTrabajo(EstadosXTrabajo idEstadoXTrabajo) {
        this.idEstadoXTrabajo = idEstadoXTrabajo;
    }

    public Tareas getIdTarea() {
        return this.idTarea;
    }

    public void setIdTarea(Tareas idTarea) {
        this.idTarea = idTarea;
    }

    public Integer getIdTareaXTrabajo() {
        return this.idTareaXTrabajo;
    }

    public void setIdTareaXTrabajo(Integer idTareaXTrabajo) {
        this.idTareaXTrabajo = idTareaXTrabajo;
    }
}
