//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "tareasXProblemas", uniqueConstraints = @UniqueConstraint(columnNames = {"idTarea", "idProblemaN3"}))

public class TareasXProblemas implements Serializable {

    @ManyToOne(optional = false, targetEntity = ProblemasN3.class)
    @JoinColumn(name = "idProblemaN3")
    private ProblemasN3 idProblemaN3;

    @ManyToOne(optional = false, targetEntity = Tareas.class)
    @JoinColumn(name = "idTarea")
    private Tareas idTarea;

    @Column(name = "idTareaXProblema", table = "tareasXProblemas", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTareaXProblema;

    public TareasXProblemas() {

    }

    public ProblemasN3 getIdProblemaN3() {
        return this.idProblemaN3;
    }

    public void setIdProblemaN3(ProblemasN3 idProblemaN3) {
        this.idProblemaN3 = idProblemaN3;
    }

    public Tareas getIdTarea() {
        return this.idTarea;
    }

    public void setIdTarea(Tareas idTarea) {
        this.idTarea = idTarea;
    }

    public Integer getIdTareaXProblema() {
        return this.idTareaXProblema;
    }

    public void setIdTareaXProblema(Integer idTareaXProblema) {
        this.idTareaXProblema = idTareaXProblema;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 73 * hash + Objects.hashCode(this.idTareaXProblema);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TareasXProblemas other = (TareasXProblemas) obj;
        if (!Objects.equals(this.idTareaXProblema, other.idTareaXProblema)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "TareasXProblemas{" + "idProblemaN3=" + idProblemaN3 + ", idTarea=" + idTarea + '}';
    }
    
}
