//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "tecnicosXTrabajos")

public class TecnicosXTrabajos implements Serializable {

    @ManyToOne(optional = false, targetEntity = EstadosXTrabajo.class)
    @JoinColumn(name = "idEstadoXTrabajo")
    private EstadosXTrabajo idEstadoXTrabajo;

    @Column(name = "idTecnicoXTrabajo", table = "tecnicosXTrabajos", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTecnicoXTrabajo;

    @ManyToOne(optional = false, targetEntity = Tecnicos.class)
    @JoinColumn(name = "idTecnico")
    private Tecnicos idTecnico;

    public TecnicosXTrabajos() {

    }

    public EstadosXTrabajo getIdEstadoXTrabajo() {
        return this.idEstadoXTrabajo;
    }

    public void setIdEstadoXTrabajo(EstadosXTrabajo idEstadoXTrabajo) {
        this.idEstadoXTrabajo = idEstadoXTrabajo;
    }

    public Integer getIdTecnicoXTrabajo() {
        return this.idTecnicoXTrabajo;
    }

    public void setIdTecnicoXTrabajo(Integer idTecnicoXTrabajo) {
        this.idTecnicoXTrabajo = idTecnicoXTrabajo;
    }

    public Tecnicos getIdTecnico() {
        return this.idTecnico;
    }

    public void setIdTecnico(Tecnicos idTecnico) {
        this.idTecnico = idTecnico;
    }
}
