//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "tecnicos")

public class Tecnicos implements Serializable {

    @OneToMany(targetEntity = EntregaInsumos.class, mappedBy = "idTecnico")
    private List<EntregaInsumos> entregaInsumosCollection;

    @Column(name = "apellido", table = "tecnicos", nullable = false, length = 45)
    @Basic
    private String apellido;

    @Column(name = "correo", table = "tecnicos", nullable = false, length = 50)
    @Basic
    private String correo;

    @OneToMany(targetEntity = Usuarios.class, mappedBy = "idTecnico")
    private List<Usuarios> usuariosCollection;

    @Column(name = "baja", table = "tecnicos", nullable = false)
    @Basic
    private boolean baja;

    @Column(name = "idTecnico", table = "tecnicos", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTecnico;

    @OneToMany(targetEntity = TecnicosXTrabajos.class, mappedBy = "idTecnico")
    private List<TecnicosXTrabajos> tecnicosXTrabajosCollection;

    @Column(name = "nombre", table = "tecnicos", nullable = false, length = 45)
    @Basic
    private String nombre;

    @ManyToOne(targetEntity = TipoEspecialidad.class)
    @JoinColumn(name = "idTipoEspecialidad")
    private TipoEspecialidad idTipoEspecialidad;

    public Tecnicos() {

    }

    public List<EntregaInsumos> getEntregaInsumosCollection() {
        return this.entregaInsumosCollection;
    }

    public void setEntregaInsumosCollection(List<EntregaInsumos> entregaInsumosCollection) {
        this.entregaInsumosCollection = entregaInsumosCollection;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public List<Usuarios> getUsuariosCollection() {
        return this.usuariosCollection;
    }

    public void setUsuariosCollection(List<Usuarios> usuariosCollection) {
        this.usuariosCollection = usuariosCollection;
    }

    public boolean isBaja() {
        return this.baja;
    }

    public void setBaja(boolean baja) {
        this.baja = baja;
    }

    public Integer getIdTecnico() {
        return this.idTecnico;
    }

    public void setIdTecnico(Integer idTecnico) {
        this.idTecnico = idTecnico;
    }

    public List<TecnicosXTrabajos> getTecnicosXTrabajosCollection() {
        return this.tecnicosXTrabajosCollection;
    }

    public void setTecnicosXTrabajosCollection(List<TecnicosXTrabajos> tecnicosXTrabajosCollection) {
        this.tecnicosXTrabajosCollection = tecnicosXTrabajosCollection;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public TipoEspecialidad getIdTipoEspecialidad() {
        return this.idTipoEspecialidad;
    }

    public void setIdTipoEspecialidad(TipoEspecialidad idTipoEspecialidad) {
        this.idTipoEspecialidad = idTipoEspecialidad;
    }
}
