//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "tipoInsumo")

public class TipoInsumo implements Serializable {

    @Column(name = "idTipoInsumo", table = "tipoInsumo", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idTipoInsumo;

    @OneToMany(targetEntity = ModelosInsumo.class, mappedBy = "idTipoInsumo")
    private List<ModelosInsumo> modelosInsumoCollection;

    @Column(name = "tipoInsumo", table = "tipoInsumo", nullable = false, length = 100)
    @Basic
    private String tipoInsumo;

    public TipoInsumo() {

    }

    public Integer getIdTipoInsumo() {
        return this.idTipoInsumo;
    }

    public void setIdTipoInsumo(Integer idTipoInsumo) {
        this.idTipoInsumo = idTipoInsumo;
    }

    public List<ModelosInsumo> getModelosInsumoCollection() {
        return this.modelosInsumoCollection;
    }

    public void setModelosInsumoCollection(List<ModelosInsumo> modelosInsumoCollection) {
        this.modelosInsumoCollection = modelosInsumoCollection;
    }

    public String getTipoInsumo() {
        return this.tipoInsumo;
    }

    public void setTipoInsumo(String tipoInsumo) {
        this.tipoInsumo = tipoInsumo;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.idTipoInsumo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TipoInsumo other = (TipoInsumo) obj;
        if (!Objects.equals(this.idTipoInsumo, other.idTipoInsumo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return tipoInsumo;
    }
    
}
