//
// This file was generated by the JPA Modeler
//
package org.legislaturachaco.sgTrabajosInformaticos.entidades;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "unidadMedida")

public class UnidadMedida implements Serializable {

    @Column(name = "abreviatura", table = "unidadMedida", nullable = false, length = 25)
    @Basic
    private String abreviatura;

    @Column(name = "unidadMedida", table = "unidadMedida", nullable = false, length = 100)
    @Basic
    private String unidadMedida;

    @OneToMany(targetEntity = ModelosInsumo.class, mappedBy = "idUnidadMedida")
    private List<ModelosInsumo> modelosInsumoCollection;

    @Column(name = "idUnidadMedida", table = "unidadMedida", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer idUnidadMedida;

    @OneToMany(targetEntity = CaracteristicasXPonderaciones.class, mappedBy = "idUnidadMedida")
    private List<CaracteristicasXPonderaciones> caracteristicasXPonderacionesCollection;

    public UnidadMedida() {

    }

    public String getAbreviatura() {
        return this.abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    public List<ModelosInsumo> getModelosInsumoCollection() {
        return this.modelosInsumoCollection;
    }

    public void setModelosInsumoCollection(List<ModelosInsumo> modelosInsumoCollection) {
        this.modelosInsumoCollection = modelosInsumoCollection;
    }

    public Integer getIdUnidadMedida() {
        return this.idUnidadMedida;
    }

    public void setIdUnidadMedida(Integer idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }

    public List<CaracteristicasXPonderaciones> getCaracteristicasXPonderacionesCollection() {
        return this.caracteristicasXPonderacionesCollection;
    }

    public void setCaracteristicasXPonderacionesCollection(List<CaracteristicasXPonderaciones> caracteristicasXPonderacionesCollection) {
        this.caracteristicasXPonderacionesCollection = caracteristicasXPonderacionesCollection;
    }
}
